/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITokenApproval,
  ITokenApprovalInterface,
} from "../../../../contracts/launchpad/interfaces/ITokenApproval";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
    ],
    name: "checkApproval",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ITokenApproval__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenApprovalInterface {
    return new utils.Interface(_abi) as ITokenApprovalInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenApproval {
    return new Contract(address, _abi, signerOrProvider) as ITokenApproval;
  }
}
