/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  AddressLib,
  AddressLibInterface,
} from "../../../../contracts/multisender/libraries/AddressLib";

const _abi = [
  {
    inputs: [],
    name: "PLATFORM_TOKEN_ADDRESS",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60a4610038600b82828239805160001a607314602b57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80638a6b856a146038575b600080fd5b605273efefefefefefefefefefefefefefefefefefefef81565b6040516001600160a01b03909116815260200160405180910390f3fea2646970667358221220168f1eaae17ac6e5994ba3f71f7745c521c5f6bcb512e0d11d831cef7c23434464736f6c63430008110033";

type AddressLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AddressLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AddressLib__factory extends ContractFactory {
  constructor(...args: AddressLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<AddressLib> {
    return super.deploy(overrides || {}) as Promise<AddressLib>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): AddressLib {
    return super.attach(address) as AddressLib;
  }
  override connect(signer: Signer): AddressLib__factory {
    return super.connect(signer) as AddressLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AddressLibInterface {
    return new utils.Interface(_abi) as AddressLibInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AddressLib {
    return new Contract(address, _abi, signerOrProvider) as AddressLib;
  }
}
